### ISSUE TITLE
element isStuck bug when element is hidden and then unhidden

### ISSUE THREAD

**Issue by eballeste** [ppowalowski/stickUp2#6]
I'm using bootstrap and am hiding/unhiding a column depending on the browsers viewport width. The element in this column that is being fixed will automatically have the stuck state even though it's not in a vertical position where the isStuck state should be triggered.

I tried using the disableOn option that returns false on smaller viewport widths with no luck and think a possible solution would be to use some type of destroy method so that I can destroy/initialize the script.

**Comment by ppowalowski** [comment]
Hey

I didn't notice this issue being open. Can you provide an example? I think we can solve this ;-)

Thanks
